### PR TITLE
Upgrade to Unity 2022.3

### LINKED ISSUE #16: Remove menu option to start the map in the game
It is broken since basically forever

### LINKED ISSUE #18: remove "play map" option from main menu
I'm not sure if it has ever worked. It has been broken for years. It should just get removed to not confuse people.

### LINKED ISSUE #20: Update Unity version
We still use the 2019 version of the editor, which is pretty old. The project should be updated.

### PR DESCRIPTION
**Pull request by MrRowey**
Closes #20 
Closes #18 
Closes #16

 @Garanas

### CODE REVIEW

**Review by Garanas — CHANGES_REQUESTED** [review]
A lot of files are deleted that feel unrelated to upgrading to the latest version. Includes for example the license, the visual studio project, the readme and the entire structure folder.

**Comment by Garanas** [comment]
But the visual studio project (`sln`) contains all the project settings. How would one edit the code and build it without it?

Unless Unity took a different approach, of course.

**Comment by MrRowey** [comment]
image
It uses Visual Studio Code Editor

**Comment by MrRowey** [comment]
jsut open up the Folder in VSCode and your able to edit all the files

**Comment by MrRowey** [comment]
Ive added back in the VS Files so they are their but it can be done via VSCode

**Comment by Garanas** [comment]
Just because it works via another tool doesn't mean we should drop Visual Studio - that's a separate concern, unrelated to upgrading the version of Unity

**Comment by BlackYps** [comment]
so uhh, how would I possiby review this immense amount of changes?

**Comment by MrRowey** [comment]
> so uhh, how would I possiby review this immense amount of changes?

This PR has so many changes due to the major change in the Unity engine this does not include any new feature additions apart from removing the play-in-game buttons.

The Best way to probably review the changes is to try the new version of the editor for Windows which is currently available for testing
https://github.com/MrRowey/FAForeverMapEditor/releases/tag/WindowsPreRelses

**Review by Garanas — APPROVED** [review]
It appears to work fine; I can't possibly verify everything of course. There are too many changes for that.

**Comment by BlackYps** [comment]
I gave the mappers time until the 19th to provide feedback, but so far I haven't heard of any issues either

**Comment by MrRowey** [comment]
> I gave the mappers time until the 19th to provide feedback, but so far I haven't heard of any issues either

That's fine we can wait for that then we can merge it in and do the new production build

**Pull request merged**
