### PR TITLE
Adding New Brushes to Build Process

### LINKED ISSUE #29: Add in CaptinKlutz TerrainBrushes in Build Process
https://github.com/CaptainKlutz/TerrainBrushes

### PR DESCRIPTION
**Pull request by MrRowey**
Closes #29 

Build process works and added the extra files https://github.com/MrRowey/FAForeverMapEditor/actions/runs/9463405473

### CODE REVIEW

**Comment by Garanas** [comment]
I'm wondering (from a security point of view) whether it is not best to add the repository as a submodule. That way you can stick to a specific commit. It provides you a way to preview the content of the submodule before updating it. Otherwise whatever is on the master branch of the repository you're including would become part of this build 🤔

**Comment by MrRowey** [comment]
would we be better off then forking that repo in the faf org that way is only updated by the faf org ?

**Comment by Garanas** [comment]
I don't know, @Sheikah45 what are your thoughts on this?

**Comment by Sheikah45** [comment]
Either a submodule or just actually add the brushes to this repo. Checking out another uncontrolled repo isn't really good practice

**Pull request closed without merging**
