### PR TITLE
Shader rework

### PR DESCRIPTION
**Pull request by BlackYps**
The aim of this PR is to reimplement the game's shaders. The existing implementation in the editor is very convoluted and can't be easily extended to more shaders that we now have in the game.
Additionally people reported lighting differences between the editor and the game.

This rework aims to provide an environment where the shaders of the game can be copy-pasted over to the editor with minimal adjustments to make it easier to spot if everything is working correctly.

During this rework I also implemented the Terrain301 shader, to test if this framework is also feasible for the different inputs that these kind of new shaders need.

The shader toggle has been changed to a text field for now. In the future this should probably be a list or radio buttons to show the available shaders, to be more user-friendly.

### CODE REVIEW

**Comment by BlackYps** [comment]
Current state:
grafik

**Comment by BlackYps** [comment]
FaTerrainShader.shader is unused now. It kept it just to be easily able to look up the old code. We could either delete the old file or copy the contents of NewFaTerrainShader.shader into this file.

**Comment by Garanas** [comment]
Can you give me pointers to what you would like me to review? I can not, for example, review the specifics of the shader code. My mathematics is simply not good enough. But I can review the code and the output in general and share my thoughts about that.

**Comment by BlackYps** [comment]
I think an in-depth shader code review is not needed. We can verify the shader code by looking at the graphical output and comparing it to the game. In other words, some testing of the functionality would be nice.
You can also compare the shader code with the game shaders from here https://github.com/FAForever/fa/blob/develop/effects/terrain.fx and give your opinion if my goal of easily being able to compare game and editor shaders succeded.
Ideally, you should be able to compare individual functions with a diff tool and only encounter differences that make sense. Comparing whole files is obviously not possible, but being able to compare on the function level was the goal.

As the current map generator maps are a bit bugged with the editor, you can use this map that I created with the changes from https://github.com/FAForever/Neroxis-Map-Generator/pull/423 to properly test out the Terrain301 shader.
[neroxis_map_generator_snapshot_sgg3i4vg2xmuu_bygaeaaiaaaaclzw.zip](https://github.com/user-attachments/files/17412556/neroxis_map_generator_snapshot_sgg3i4vg2xmuu_bygaeaaiaaaaclzw.zip)

**Comment by BlackYps** [comment]
I originally planned to only change the terrain shader here and to make a separate PR for the water and props shader. But I noticed that it's probaby less effort for everyone to have everything at once. This way you only have to test once and everything already looks like it should.
Note that the diffs become a bit unwieldly, because I moved the orginally separate files with the new shader code into the old ones in the second-to-last commit. There is no reason to keep the old, unused code. If you want to have a cleaner look at the files (again, no deep review required there, we can simply verify the visual result), you can either view the file directly or exclude that commit in the diff.

**Pull request merged**
